### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Macer-cpp** [fuckinmoney/Discord_Group_Spammer#4]
![image](https://user-images.githubusercontent.com/91558715/140755418-664bd2e8-d311-4bdc-abcb-39e33cfefd20.png)

I am receiving this message, all libraries are installed.

**Comment by ToBeatELIT3** [comment]
you need to put a real directory for the image "imagePath"
C:/Users/image/cool.jpg is a placeholder, the exception occurs because it cant find it (its not there on your computer)

FIX:
change the "imagePath" string to point to a valid image

**Comment by FuckingToaster** [comment]
> ![image](https://user-images.githubusercontent.com/91558715/140755418-664bd2e8-d311-4bdc-abcb-39e33cfefd20.png)
> 
> I am receiving this message, all libraries are installed.

you open the file "imagepath in read byte mode what you defently should avoid. i made a pull request with a updated code that works and is even better. it got merged so you should try to use this one.
